-- -- Users table seeds here (Example)
-- INSERT INTO users
--   (email, password)
-- VALUES
--   ('Alice@gmail.com' , 'ab43uhD');
-- INSERT INTO users
--   (email, password)
-- VALUES
--   ('Paul@hotmail.com' , '0943gtS');
