INSERT INTO books (item_id, title, author, pages, image, publication_year, rating, description, is_active)
  VALUES
   (1, 'Harry Potter and the Cursed Child: Parts one and two', 'J.K. Rowling', 407, 'https://books.google.ca/books/content?id=cvRFvgAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE700XSQS1ZqXallBsOWHaXkokc3yoofRtVYIbw-KpwqSMziAq5ICvRykORCFCvlqmcx9OpWCJ5YWnFgo8gTm1scjuF3GyeGS1kxzwVTrfvHnuZQ0Eu9d5S3ErQs8ObNz_8XCTJbr', '2016-01-01', 5, 'Based on an original new story by J.K. Rowling, John Tiffany, and Jack Thorne, a new play by Jack Thorne, Harry Potter and the Cursed Child is the eighth story in the Harry Potter series and the first official Harry Potter story to be presented...', TRUE),

   (3, 'The Fellowship of the Ring: Being the First Part of the Lord of the Rings', 'John Ronald Reuel Tolkien', 531, 'https://books.google.ca/books/content?id=_FjrugAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE72xNivd-_8jvUKLywUo8-r6S4o4g1tTQheweHcWuy8RvA6tUL4j9SzFPSMPbcSGe6kv_nwhUBH4YaE2NRcL7jiVVn9hz7hr7k_g3OInfcXQzBMUUA0spG7Y3HEXc01ErpYKgXx6', '2012-01-01', 5, 'Continuing the story begun in The Hobbit, this is the first part of Tolkien s epic masterpiece, The Lord of the Rings, featuring an exclusive cover image from the film, the definitive text, and a detailed map of Middle-earth.', TRUE),

   (6, 'The Polar Express', 'Chris Van Allsburg', 32, 'https://books.google.ca/books/content?id=FmQ0nwEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE714N7N5ne_CckILBcKzw-U7FgkrUQQsB-eHrSFA4KogvGUud64OmMgdevIA_vxMVujb3AuZQmkeILkZyk6JBVW2BIPD47ZcWSoxCmST2yfx2qAs_yoXTPPXvi-leDYGT_9Z_K2I', '2014-01-01', 5, 'Late on Christmas Eve, after the town has gone to sleep, a boy boards a mysterious train that waits for him- the Polar Express bound for the North Pole. When he arrives there, Santa offers him any gift he desires. The boy modestly asks...', TRUE),

   (10, 'The Twits', 'Roald Dahl', 100, 'https://books.google.ca/books/content?id=JwQ-mgEACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE70BhATY7vfuRO0HT12zipm2-HOYsGH-MuDbWlTOSc8MTkRc_i0225QA8_CVfSieJrhGNsmqDzm9wOVWMXWsNVCieLaIYocMWEcYRi_N9YTtbQp2MEUFuUNAYs4KxJA7UekeGsf2', '2013-01-01', 4.5, 'Puffin Audiobooks presents a marvellous new reading of Roald Dahl/s The Twits read by IT Crowd star Richard Ayoade. The audiobook features original music. Mr Twit is a foul and smelly man with bits of cornflake and sardine in his...', TRUE),

   (15, 'Superbad: The Illustrated Moviebook', 'Seth Rogen', 144, 'https://books.google.ca/books/content?id=R2gOPQAACAAJ&printsec=frontcover&img=1&zoom=1&imgtk=AFLRE73TTmzaIE6Dogh8qyY1NbUkuE-aAUv9ofFElF1qtmE9wQ8dEXqcUcQxngyu3cSEubm4YSSG2SzI1dg7O7TjHuB7HvPnjykbI_Bz_ohALYxehrXj96w3BlLCO2sQWmvOEqTKkKVL', '2007-01-01', 0, 'The official book tie-in to the hilarious blockbuster film, including the complete screenplay, movie stills, and outrageous drawings that millions of fans will recognize from the film.', TRUE);
