DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products
  (
    id SERIAL PRIMARY KEY NOT NULL,
    item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    cost INTEGER  NOT NULL DEFAULT 0,
    buy_reference VARCHAR(500),
    rating SMALLINT NOT NULL DEFAULT 0,
    image VARCHAR(500),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT FALSE
  );
